name: astgrief
main: com.nullptr.astgrief.Main
version: 0.1
commands:
  khelp:
      description: Help Command
      usage: /khelp
      permission: astgrief.player
  kdiamonds:
      description: Spawn Diamonds Command
      usage: /kdiamonds
      permission: astgrief.medium
  kboom:
      description: Boom Command
      usage: /kboom
      permission: astgrief.admin
  kheal:
      description: Heal Command
      usage: /kheal
      permission: astgrief.medium
  kthor:
      description: Thor Command
      usage: /kthor
      permission: astgrief.admin
