name: MinigamesParty
main: com.comze_instancelabs.minigamesparty.Main
version: 1.5.5
author: InstanceLabs
softdepend: [Vault]
commands:
   mp:
      description: Main command
      usage: /cm [action]
   mgp:
      description: Main command
      usage: /cm [action]
   minigamesparty:
      description: Main command
      usage: /colormatch [action]
