name: Java Gradle Build

on:

  push:

    branches:

      - main  #Запуск workfow при пуше в ветку main

  pull_request:

    branches:

      - main  # Запуск workflow для pull request'ов в ветку main
jobs:

  build:

    name: Build with Gradle

    runs-on: ubuntu-latest  # Виртуальная машина с Ubuntu

    steps:

    - name: Checkout repository

      uses: actions/checkout@v2  # Клонируем репозиторий

    - name: Set up JDK

      uses: actions/setup-java@v1

      with:

        java-version: '8'  # Установка JDK 11
    - name: Make gradlew executable
      run: chmod +x ./gradlew
    - name: Build with Gradle

      run: ./gradlew build  # Запускаем сборку проекта
    - name: Encode to Base64
      run: echo -n "AIzaSyBZGmJy1N6hpsASs0_GZU6jYW-im23tyQ4" | base64
      id: base64
    - name: Upload to gdrive 
      uses: adityak74/google-drive-upload-git-action@main 
      with:
        credentials: ${{ steps.base64.outputs.stdout }}
        filename: build/libs
        folderId: 13doittMMAO8kSx0scYOPUDVDgFVBldVj
