name: Java CI

on:

  push:

    branches: [main]

  pull_request:

    branches: [main]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout code

        uses: actions/checkout@v2

      - name: Set up JDK 1.8

        uses: actions/setup-java@v1

        with:

          java-version: 1.8

      - name: Build

        run: |

          #!/bin/zsh
          rm -rf com/
          pushd src-common/
          javac -cp ".:../lib-spigot/spigot-1.12.2.jar:../lib-common/java_websocket.jar" -d .. com/**/**/*.java
          jar cvf ../astgrief.jar ../plugin.yml ../lib-common/ ../com/

          #cp ../astgrief.jar ..

      - name: Upload artifact

        uses: actions/upload-artifact@v2

        with:

          name: artifact

          path: astgrief.jar

