name: Java CI

on:

  push:

    branches: [main]

  pull_request:

    branches: [main]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout code

        uses: actions/checkout@v2

      - name: Set up JDK 1.8

        uses: actions/setup-java@v1

        with:

          java-version: 1.8

      - name: Build

        run: |

          #!/bin/zsh

          rm -rf com/

          pushd src-common/

          javac -cp ".:../lib-spigot/spigot-1.12.2.jar:../lib-common/java_websocket.jar" -d .. com/**/**/*.java

          jar cvf ../astgrief.jar ../plugin.yml ../lib-common/ ../com/

      - name: Install SFTP client and Expect

        run: |

          sudo apt-get update

          sudo apt-get install -y lftp expect

      - name: Create Expect Script File

        run: |

          echo 'spawn lftp -d -e "' >> sftp_script.expect

          echo 'set sftp:connect-program '\''sshpass -e ssh'\'';' >> sftp_script.expect

          echo 'set ssl:verify-certificate no;' >> sftp_script.expect

          echo 'open -p 2022 -u ksgo87265.c58690ff,$env(SSHPASS) d1.aurorix.net;' >> sftp_script.expect

          echo 'expect {' >> sftp_script.expect

          echo '  "Password:" {' >> sftp_script.expect

          echo '    send "$env(SSHPASS)\r";' >> sftp_script.expect

          echo '    exp_continue;' >> sftp_script.expect

          echo '  }' >> sftp_script.expect

          echo '  "sftp>" {' >> sftp_script.expect

          echo '    send "put -O ./plugins/ astgrief.jar\r";' >> sftp_script.expect

          echo '  }' >> sftp_script.expect

          echo '}' >> sftp_script.expect

          echo 'exit;' >> sftp_script.expect

      - name: FTP Transfer

        env:

          SSHPASS: "12980987"

        run: |

          expect sftp_script.expect

