name: Java CI

on:

  push:

    branches: [main]

  pull_request:

    branches: [main]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout code

        uses: actions/checkout@v2

      - name: Set up JDK 1.8

        uses: actions/setup-java@v1

        with:

          java-version: 1.8

      - name: Build

        run: |

          #!/bin/zsh
          rm -rf com/
          pushd src-common/
          javac -cp ".:../lib-spigot/spigot-1.12.2.jar:../lib-common/java_websocket.jar" -d .. com/**/**/*.java
          jar cvf ../astgrief.jar ../plugin.yml ../lib-common/ ../com/

          #cp ../astgrief.jar ..

      - name: Install SFTP client and Expect
        run: |
             sudo apt-get update
             sudo apt-get install -y lftp expect

      - name: Upload artifact to SFTP server
        run: |

             # Создаем временный файл expect-скрипта

             echo "spawn lftp -u $ksgo87265.c58690ff,$12980987 $d1.aurorix.net -p 2022" > sftp_script

             echo "set sftp:auto-confirm yes" >> sftp_script
  
             echo "cp astgrief.jar /plugins/" >> sftp_script

             echo "exit" >> sftp_script

             # Вызываем expect, передавая ему наш временный скрипт

             expect -f sftp_script
