name: Java CI

on:

  push:

    branches: [main]

  pull_request:

    branches: [main]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout code

        uses: actions/checkout@v2

      - name: Set up JDK 1.8

        uses: actions/setup-java@v1

        with:

          java-version: 1.8

      - name: Build

        run: |

          #!/bin/zsh
          rm -rf com/
          pushd src-common/
          javac -cp ".:../lib-spigot/spigot-1.12.2.jar:../lib-common/java_websocket.jar" -d .. com/**/**/*.java
          jar cvf ../astgrief.jar ../plugin.yml ../lib-common/ ../com/

          #cp ../astgrief.jar ..

      - name: Install SFTP client and Expect
        run: |
             sudo apt-get update
             sudo apt-get install -y lftp

      - name: Upload artifact to SFTP server
        run: |
             # Создаем временный файл expect-скрипта
             export SSHPASS="12980987"
             lftp -d -e "debug; set sftp:connect-program 'sshpass -e ssh'; set ssl:verify-certificate no; open -p 2022 -u ksgo87265.c58690ff,${SSHPASS} d1.aurorix.net; put astgrief.jar /plugins/; ls -l"
