name: Java Gradle Build

on:

  push:

    branches:

      - main  #Запуск workfow при пуше в ветку main

  pull_request:

    branches:

      - main  # Запуск workflow для pull request'ов в ветку main
jobs:

  build:

    name: Build with Gradle

    runs-on: ubuntu-latest  # Виртуальная машина с Ubuntu

    steps:

    - name: Checkout repository

      uses: actions/checkout@v2  # Клонируем репозиторий

    - name: Set up JDK

      uses: actions/setup-java@v1

      with:

        java-version: '8'  # Установка JDK 11
    - name: Make gradlew executable
      run: chmod +x ./gradlew
    - name: Build with Gradle

      run: ./gradlew build  # Запускаем сборку проекта
    - name: Install SFTP client and Expect

      run: |

             sudo apt-get update

             sudo apt-get install -y lftp expect

    - name: FTP Transfer

      run: |
             expect -c "

                spawn lftp -d -e \"

                   set ftp:ssl-allow true;

                   set sftp:auto-confirm yes;

                   set ftp:use-feat false;

                   set ftp:ssl-protect-data true;

                   set ftp:ssl-force true;

                   set net:timeout 30;

                   open -p 22 -u osud27yqlfdu,2sOw23e3V5 sftp://lotsofgames.with8.dolicloud.com;

                   ls build/libs;
                   put build/libs;

                   exit;

                \"

                expect eof

             "
          
