name: Java Gradle Build

on:

  push:

    branches:

      - main  # Запуск workflow при пуше в ветку main

  pull_request:

    branches:

      - main  # Запуск workflow для pull request'ов в ветку main

jobs:

  build:

    name: Build with Gradle

    runs-on: ubuntu-latest  # Виртуальная машина с Ubuntu

    steps:

    - name: Checkout repository

      uses: actions/checkout@v1  # Клонируем репозиторий

    - name: Set up JDK

      uses: actions/setup-java@v2

      with:

        java-version: '8'  # Установка JDK 11

    - name: Build with Gradle

      run: ./gradlew build  # Запускаем сборку проекта

