name: Java CI

on:

  push:

    branches: [main]

  pull_request:

    branches: [main]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout code

        uses: actions/checkout@v2

      - name: Set up JDK 1.8

        uses: actions/setup-java@v1

        with:

          java-version: 1.8

      - name: Build

        run: |

          #!/bin/zsh

          rm -rf com/

          #pushd src-common/
          pushd src/

          #javac -cp ".:../lib-spigot/spigot-1.12.2.jar:../lib-common/java_websocket.jar" -d .. com/**/**/*.java
          javac -cp ".:../lib-spigot/spigot-1.8.8-R0.1-SNAPSHOT-latest.jar:../lib-spigot/Vault.jar" -d .. com/**/**/*.java
          jar cvf ../astgrief.jar ../plugin.yml ../com/

          #cp ../astgrief.jar ..

      - name: Install SFTP client and Expect

        run: |

             sudo apt-get update

             sudo apt-get install -y lftp expect

      - name: FTP Transfer

        run: |
             expect -c "

                spawn lftp -d -e \"

                   set ftp:ssl-allow true;

                   set sftp:auto-confirm yes;

                   set ftp:use-feat false;

                   set ftp:ssl-protect-data true;

                   set ftp:ssl-force true;

                   set net:timeout 30;

                   open -p 2022 -u ksgo87265.c58690ff,12980987 sftp://d1.aurorix.net;

                   cd plugins;

                   put astgrief.jar;

                   exit;

                \"

                expect eof

             "
          
