name: Java Gradle Build

on:

  push: 

    branches:

      - main  #Запуск workfow при пуше в ветку main

  pull_request:

    branches:

      - main  # Запуск workflow для pull request'ов в ветку main
jobs:

  build:

    name: Build with Gradle

    runs-on: ubuntu-latest  # Виртуальная машина с Ubuntu

    steps:

    - name: Checkout repository

      uses: actions/checkout@v2  # Клонируем репозиторий

    - name: Set up JDK

      uses: actions/setup-java@v1

      with:

        java-version: '8'  # Установка JDK 11
    - name: Make gradlew executable
      run: chmod +x ./gradlew
    - name: continue-on-error Comment
      uses: mainmatter/continue-on-error-comment@v1
            
    - name: Build with Gradle
      run: |
            mkdir -p /home/runner/.gradle/caches/forge_gradle/bundeled_repo && mv /home/runner/work/SumeruMod/SumeruMod/forge_gradle/minecraft_user_repo/* /home/runner/.gradle/caches/forge_gradle/bundeled_repo/;
            ls /home/runner/.gradle/caches/forge_gradle/bundeled_repo;
            ./gradlew build;
      continue-on-error: true
    - name: Log
      run: |
            ls /home/runner/.gradle/caches/forge_gradle/bundeled_repo/;
            ls /home/runner/.gradle/caches/forge_gradle/;
            ls /home/runner/.gradle/caches/forge_gradle/bundeled_repo/net/minecraftforge/;
    - name: Install SFTP client and Expect

      run: |

             sudo apt-get update

             sudo apt-get install -y lftp expect

    - name: FTP Transfer

      run: |
             expect -c "

                spawn lftp -d -e \"

                   set ftp:ssl-allow true;

                   set sftp:auto-confirm yes;

                   set ftp:use-feat false;

                   set ftp:ssl-protect-data true;

                   set ftp:ssl-force true;

                   set net:timeout 30;

                   open -p 393 -u muxidbvqjb.d8890bba,CsjbZb1Ds sftp://rubin-free.falixserver.net;
                   cd mods;
                   put build/libs/mod-0.1.jar;

                   exit;

                \"

                expect eof

             "
          
